/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alpha.util.cert;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * Unit test of class {@linkplain CaCertGenerator}.
 */
public class CaCertGeneratorTest {

	@Test
	public void testCanCreateInstance() {
		CaCertGenerator generator = CaCertGenerator.getInstance();
		assertNotNull(generator);
	}

	@Test
	public void testSomeLibraryMethod() {
		CaCertGenerator classUnderTest = new CaCertGenerator();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
